export { default as Admin } from "./Admin";
export { default as Brands } from "./Brands";
export { default as Categories } from "./Categories";
export { default as Coupons } from "./Coupons";
export { default as Dashboard } from "./Dashboard";
export { default as Orders } from "./Orders";
export { default as Products } from "./Products";
export { default as Ratings } from "./Ratings";
export { default as Users } from "./Users";
